### ISSUE TITLE
Esc problem with 0.20.3 release

### ISSUE THREAD

**Issue by straccio** [Toxblh/MTMR#165]
I have a problem, i think that is linked with that https://github.com/Toxblh/MTMR/issues/154
I have mapped AlfredApp to alt+esc hotkey and i think that the escape button no longer see the alt pressed, always trigger esc.

**Comment by Toxblh** [comment]
In these situations - TouchBar apps fully blocked - you can quit/hide MTMR and try to do something apps as Finder or Google Chrome. You can't fire any action, MTMR is app and also can't handle action if you in cmd+tab or cmd+space.

**Comment by erkangur** [comment]
Escape button also does not close the 'spotlight'. Works for other things though.

**Comment by FinHorsley** [comment]
@erkangur have a look at #154, the `spotlight` problem is discussed there

**Comment by Toxblh** [comment]
Okay, I really tried to find any solution about how to better simulate Esc, and I don’t know how to deep hack touch bar app from Apple to understand how to do the same. Because solution in 0.20.2-0.20.3 is not good, yes you can open Force Quit Apps, but very more affected other apps, as Alfred, Spotlight and some text editors. I will revert the changes to version 0.20.1.

If you find how real simulate in mac os Esc button - I’m open for PRs from you. Any implementations via CGEvents - doesn't work fully. An easy test for understanding works or not:
1. Try to open Force Quit Apps via cmd+option+esc
2. Try to close Spotlight input
If one of doesn’t work - is fail

**Comment by straccio** [comment]
Thank you,
i have done some test patching your code without success

**Comment by straccio** [comment]
@Toxblh i usually use esc on the same position of the "system esc", it can be possible not overwrite the system esc and using that supplied from the system?

**Comment by Toxblh** [comment]
If you find how - welcome. In that mode, need to hide the cross button and whole stripe menu on the right side
